#!/bin/sh


timedatectl set-timezone Europe/Stockholm
cp upmpdcli.list /etc/apt/sources.list.d
cp gdis.dtbo /boot/overlays

apt-get update
apt-get install dirmngr
apt-key adv --keyserver pool.sks-keyservers.net --recv-keys F8E3347256922A8AE767605B7808CE96D38B9201
apt-get update
apt-get install python3 python3-pip python3-setuptools mpd mpc upmpdcli upmpdcli-tidal squeezelite git-core autoconf make libtool libfftw3-dev libasound2-dev build-essential git-core autoconf make libtool libi2c-dev i2c-tools lm-sensors libcurl4-openssl-dev libmpdclient-dev libjsoncpp-dev -y --allow-unauthenticated
cp mpd.conf /etc/mpd.conf
mv /etc/upmpdcli.conf /etc/upmpdcli.conf.orig
cp upmpdcli.conf /etc/upmpdcli.conf
mv /etc/init.d/squeezelite /etc/squeezelite
cp squeezelite /etc/default/squeezelite
cp overlayRoot.sh /usr/local/sbin/overlayRoot.sh
chmod +x /usr/local/sbin/overlayRoot.sh
dphys-swapfile swapoff
dphys-swapfile uninstall
update-rc.d dphys-swapfile remove

sed -i '$ i init=/usr/local/sbin/overlayRoot.sh' /boot/cmdline.txt

sed -i '/dtparam=audio=on/d' /boot/config.txt
sed -i '$ i dtoverlay=gdis' /boot/config.txt
sed -i '$ i dtparam=i2c_arm_baudrate=400000' /boot/config.txt
sed -i '$ i dtparam=i2c_arm=on' /boot/config.txt
sed -i '$ i i2c-dev' /etc/modules
sed -i '$ i python3 /root/app.py &' /etc/rc.local
sed -i '$ i mpd_oled -o 6 -b 21 -g 1 -f 15 -R &' /etc/rc.local
sed -i '$ i sleep 9' /etc/rc.local
sed -i '$ i echo "4" > /sys/class/gpio/export' /etc/rc.local
sed -i '$ i echo "out" > /sys/class/gpio/gpio4/direction' /etc/rc.local
sed -i '$ i mpc volume 50' /etc/rc.local

pip3 install flask

echo
echo "---Insalling cava---"
sleep 3

cd /root
git clone https://github.com/karlstav/cava
cd cava
./autogen.sh
./configure
make
make install

echo
echo "---Installing OLED---"
sleep 3

cd /root
git clone https://github.com/antiprism/mpd_oled
cd mpd_oled
PLAYER=MPD make
cp mpd_oled /usr/local/bin

reboot
