#!/bin/sh


timedatectl set-timezone Europe/Stockholm
cp gdis.dtbo /boot/overlays
cp mountusb /root
cp umountusb /root

apt-get update
apt-get install dirmngr -y
apt-key adv --keyserver pool.sks-keyservers.net --recv-keys F8E3347256922A8AE767605B7808CE96D38B9201
cp upmpdcli.list /etc/apt/sources.list.d
apt-get update
apt-get install python-pip python-setuptools mpd mpc upmpdcli upmpdcli-tidal squeezelite minidlna i2c-tools python-dev python-smbus python-mpd python-flask python-wheel libfreetype6-dev libjpeg-dev build-essential -y --allow-unauthenticated
cp mpd.conf /etc/mpd.conf
mv /etc/upmpdcli.conf /etc/upmpdcli.conf.orig
cp upmpdcli.conf /etc/upmpdcli.conf
cp minidlna.conf /etc/minidlna.conf
mv /etc/init.d/squeezelite /etc/squeezelite
cp squeezelite /etc/default/squeezelite
dphys-swapfile swapoff
dphys-swapfile uninstall
update-rc.d dphys-swapfile remove
update-rc.d minidlna defaults

sed -i '/dtparam=audio=on/d' /boot/config.txt
sed -i '$ i dtoverlay=gdis' /boot/config.txt
sed -i '$ i dtparam=i2c_arm_baudrate=400000' /boot/config.txt
sed -i '$ i dtparam=i2c_arm=on' /boot/config.txt
sed -i '$ i dtparam=pwr_led_trigger=none' /boot/config.txt
sed -i '$ i dtparam=pwr_led_activelow=off' /boot/config.txt
sed -i '$ i dtoverlay=pi3-act-led' /boot/config.txt
sed -i '$ i dtparam=act-led-trigger=none' /boot/config.txt
sed -i '$ i i2c-dev' /etc/modules
sed -i '$ i python /root/pi3/app.py &' /etc/rc.local
sed -i '$ i python /root/pi3/oled/oled.py &' /etc/rc.local
sed -i '$ i bash /root/mountusb &' /etc/rc.local
sed -i '$ i sleep 9' /etc/rc.local
sed -i '$ i echo "4" > /sys/class/gpio/export' /etc/rc.local
sed -i '$ i echo "out" > /sys/class/gpio/gpio4/direction' /etc/rc.local
sed -i '$ i mpc volume 50' /etc/rc.local

echo
echo "---Insalling roon---"
sleep 3

cd /root
curl -O http://download.roonlabs.com/builds/roonbridge-installer-linuxarmv7hf.sh
chmod +x roonbridge-installer-linuxarmv7hf.sh
yes yes | ./roonbridge-installer-linuxarmv7hf.sh

echo
echo "---Installing OLED---"
sleep 3

pip install --upgrade luma.oled

echo
echo "---Insalling overlayroot---"
sleep 3

mkdir /ro
sed -i '$ i mount -o ro /dev/mmcblk0p2 /ro' /etc/rc.local
echo overlay > /etc/initramfs-tools/modules
cd /root/pi3
cp overlay /etc/initramfs-tools/scripts
update-initramfs -c -k $(uname -r)
mv /boot/initrd.img-$(uname -r) /boot/initrd.img
sed -i '$ a initramfs initrd.img' /boot/config.txt
sed -i 's/^/boot=overlay /' /boot/cmdline.txt

echo 
echo "##############################################"
echo                      REBOOT
echo "##############################################"
sleep 2

reboot
