#!/bin/sh


timedatectl set-timezone Europe/Stockholm
cp mountusb /root
cp umountusb /root


gpg --keyserver pool.sks-keyservers.net --recv-key F8E3347256922A8AE767605B7808CE96D38B9201
gpg --export '7808CE96D38B9201' | apt-key add -
add-apt-repository ppa:jean-francois-dockes/upnpp1

apt-get install curl lirc python-pip mpd mpc upmpdcli upmpdcli-tidal shairport-sync squeezelite minidlna i2c-tools python-dev python-smbus python-mpd python-flask libfreetype6-dev libjpeg-dev build-essential -y --allow-unauthenticated
cp mpd.conf /etc/mpd.conf
cp lircrc /etc/lirc
cp input /boot
cp gdis.lircd.conf /etc/lirc/lircd.conf.d
cp lirc_options.conf /etc/lirc
mv /etc/upmpdcli.conf /etc/upmpdcli.conf.orig
cp upmpdcli.conf /etc/upmpdcli.conf
cp minidlna.conf /etc/minidlna.conf
cp gdis_upnp.png /boot
cp ready.wav streamer.wav coaxial.wav optical.wav wifi.wav ethernet.wav /root
cp shairport-sync.conf /etc/shairport-sync.conf
mv /etc/init.d/squeezelite /etc/squeezelite
cp squeezelite /etc/default/squeezelite
update-rc.d minidlna defaults
cp oled2.service /etc/systemd/system
cp oled.service /etc/systemd/system
systemctl enable oled

sed -i '$ i i2c-dev' /etc/modules
sed -i '$ i aml_i2c' /etc/modules
sed -i '$ i python /root/pi3/app.py &' /etc/rc.local
sed -i '$ i bash /root/mountusb &' /etc/rc.local
#sed -i '$ i mpc volume 50' /etc/rc.local
#sed -i '$ i aplay /root/ready.wav' /etc/rc.local
sed -i '$ i irexec &' /etc/rc.local
sed -i '$ i python /root/pi3/default.py' /etc/rc.local

echo
echo "---Insalling roon---"
sleep 3

cd /root
curl -O http://download.roonlabs.com/builds/roonbridge-installer-linuxarmv7hf.sh
chmod +x roonbridge-installer-linuxarmv7hf.sh
yes yes | ./roonbridge-installer-linuxarmv7hf.sh

echo
echo "---Installing OLED---"
sleep 3

python -m pip install --upgrade pip setuptools wheel
pip install --upgrade luma.oled


echo 
echo "##############################################"
echo                      REBOOT
echo "##############################################"
sleep 2

reboot
